name: Run Spotify App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list >/dev/null
          sudo apt update && sudo apt install ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Run application with ngrok
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REDIRECT_URI: ${{ secrets.SPOTIFY_REDIRECT_URI }}
          STREAMLIT_BROWSER_GATHER_USAGE_STATS: false
          STREAMLIT_HEADLESS: true
        run: |
          nohup streamlit run src/app/app.py --server.port 8501 --server.address 0.0.0.0 &
          sleep 5
          ngrok http 8501 > ngrok.log &
          sleep 5
          cat ngrok.log | grep -o "https://[a-z0-9]*\.ngrok\.io" > ngrok_url.txt
          echo "Your app is available at: $(cat ngrok_url.txt)"

      - name: Upload ngrok URL
        uses: actions/upload-artifact@v4
        with:
          name: ngrok-url
          path: ngrok_url.txt