[theme]
primaryColor = "#1DB954"       # Spotify green
backgroundColor = "#000000"    # Black
secondaryBackgroundColor = "#121212"  # Slightly lighter black
textColor = "#FFFFFF"          # White
font = "sans serif"